# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: slate.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'slate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bslate.proto\x12\x05slate\"\x1f\n\x0c\x46ocusRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x1b\n\rFocusResponse\x12\n\n\x02id\x18\x01 \x01(\t\"\x0e\n\x0c\x44riftRequest\"/\n\rDriftResponse\x12\x1e\n\x05items\x18\x01 \x03(\x0b\x32\x0f.slate.FluxItem\":\n\x08\x46luxItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\trelevance\x18\x03 \x01(\x02\"o\n\x05Trace\x12\r\n\x05input\x18\x01 \x01(\t\x12\x11\n\treasoning\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x0f\n\x07outcome\x18\x04 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x05 \x01(\t\x12\x11\n\tembedding\x18\x06 \x03(\x02\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\"E\n\rRecallRequest\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\r\n\x05limit\x18\x02 \x01(\x04\x12\x12\n\nquery_text\x18\x03 \x01(\t\".\n\x0eRecallResponse\x12\x1c\n\x06traces\x18\x01 \x03(\x0b\x32\x0c.slate.Trace\"D\n\x0cQueryRequest\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\r\n\x05limit\x18\x02 \x01(\x04\x12\x12\n\nquery_text\x18\x03 \x01(\t\"/\n\x11KnowledgeResponse\x12\x1a\n\x05\x66\x61\x63ts\x18\x01 \x03(\x0b\x32\x0b.slate.Fact\"3\n\x04\x46\x61\x63t\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\"#\n\rReflexRequest\x12\x12\n\nskill_name\x18\x01 \x01(\t\"!\n\x0f\x45xecutionResult\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xc1\x02\n\x06\x43ortex\x12\x32\n\x05\x46ocus\x12\x13.slate.FocusRequest\x1a\x14.slate.FocusResponse\x12\x32\n\x05\x44rift\x12\x13.slate.DriftRequest\x1a\x14.slate.DriftResponse\x12\"\n\x06\x43ommit\x12\x0c.slate.Trace\x1a\n.slate.Ack\x12\x38\n\tReminisce\x12\x14.slate.RecallRequest\x1a\x15.slate.RecallResponse\x12\x38\n\x07\x43onsult\x12\x13.slate.QueryRequest\x1a\x18.slate.KnowledgeResponse\x12\x37\n\x07Trigger\x12\x14.slate.ReflexRequest\x1a\x16.slate.ExecutionResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'slate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FOCUSREQUEST']._serialized_start=22
  _globals['_FOCUSREQUEST']._serialized_end=53
  _globals['_FOCUSRESPONSE']._serialized_start=55
  _globals['_FOCUSRESPONSE']._serialized_end=82
  _globals['_DRIFTREQUEST']._serialized_start=84
  _globals['_DRIFTREQUEST']._serialized_end=98
  _globals['_DRIFTRESPONSE']._serialized_start=100
  _globals['_DRIFTRESPONSE']._serialized_end=147
  _globals['_FLUXITEM']._serialized_start=149
  _globals['_FLUXITEM']._serialized_end=207
  _globals['_TRACE']._serialized_start=209
  _globals['_TRACE']._serialized_end=320
  _globals['_ACK']._serialized_start=322
  _globals['_ACK']._serialized_end=344
  _globals['_RECALLREQUEST']._serialized_start=346
  _globals['_RECALLREQUEST']._serialized_end=415
  _globals['_RECALLRESPONSE']._serialized_start=417
  _globals['_RECALLRESPONSE']._serialized_end=463
  _globals['_QUERYREQUEST']._serialized_start=465
  _globals['_QUERYREQUEST']._serialized_end=533
  _globals['_KNOWLEDGERESPONSE']._serialized_start=535
  _globals['_KNOWLEDGERESPONSE']._serialized_end=582
  _globals['_FACT']._serialized_start=584
  _globals['_FACT']._serialized_end=635
  _globals['_REFLEXREQUEST']._serialized_start=637
  _globals['_REFLEXREQUEST']._serialized_end=672
  _globals['_EXECUTIONRESULT']._serialized_start=674
  _globals['_EXECUTIONRESULT']._serialized_end=707
  _globals['_CORTEX']._serialized_start=710
  _globals['_CORTEX']._serialized_end=1031
# @@protoc_insertion_point(module_scope)
